name: PHP Composer Install

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install
      working-directory: ${{ env.GITHUB_WORKSPACE }}

    - name: Save vendor and web directory to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global core.autocrlf false
        git add vendor web
        git commit -m "Add vendor and web directory"
        git push