name: PHP Composer Install

on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "ramsey/composer-install@v2"
        with:
          ignore-cache: "yes"
      - uses: "marvinpinto/action-automatic-releases@latest"
                with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                    ./*
