name: PHP Composer Install

on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: "ramsey/composer-install@v2"
        with:
          ignore-cache: "yes"

      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./
      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag_name: ${{  github.ref_name }}
          release_name: Release ${{  github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: /tmp/github-actions/build.tar
          asset_name: asset-name
          asset_content_type: application/zip
